# Generated by Django 5.2.5 on 2025-08-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='persona',
        ),
        migrations.AlterModelOptions(
            name='escuela',
            options={'verbose_name': 'Escuela', 'verbose_name_plural': 'Escuelas'},
        ),
        migrations.RemoveField(
            model_name='director',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='matricula',
        ),
        migrations.AddField(
            model_name='director',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='director',
            name='escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directores', to='personal.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='alumnos_manana',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de alumnos mañana'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='alumnos_tarde',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de alumnos tarde'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='cantidad_directores',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de directores'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='cantidad_grados_manana',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de grados mañana'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='cantidad_grados_tarde',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de grados tarde'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='cantidad_maestros',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de maestros'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=200, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escuela',
            name='recibe_fondo_comedor',
            field=models.BooleanField(default=False, verbose_name='Recibe fondo para comedores'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='tiene_gabinete',
            field=models.BooleanField(default=False, verbose_name='Gabinete profesional'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='tiene_porteros',
            field=models.BooleanField(default=False, verbose_name='Porteros'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='turno_manana',
            field=models.BooleanField(default=True, verbose_name='Turno mañana'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='turno_tarde',
            field=models.BooleanField(default=False, verbose_name='Turno tarde'),
        ),
        migrations.AlterField(
            model_name='director',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='director',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='director',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='localidad',
            field=models.CharField(max_length=100, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de la escuela'),
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('alumnos_a_cargo', models.PositiveIntegerField(default=0, verbose_name='Cantidad de alumnos a cargo')),
                ('cumple_ordenes', models.BooleanField(default=True, verbose_name='Cumple órdenes')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maestros', to='personal.escuela', verbose_name='Escuela')),
            ],
            options={
                'verbose_name': 'Maestro/a',
                'verbose_name_plural': 'Maestros/as',
            },
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
